import { ToolRegistry } from '../core/tool/index.js';
import { floatingPromises } from './async/floating-promises/floating-promises.js';
import { llmTells } from './comments/llm-tells/llm-tells.js';
import { longComments } from './comments/long/long.js';
import { staleRefs } from './comments/stale-refs/stale-refs.js';
import { dupeFunctions } from './dupes/functions/functions.js';
import { importCycles } from './graph/cycles/cycles.js';
import { deadExports } from './graph/dead-exports/dead-exports.js';
import { changeSignature } from './refactors/change-signature/change-signature.js';
import { constructorToFactory } from './refactors/constructor-to-factory/constructor-to-factory.js';
import { enumToConstObject } from './refactors/enum-to-const-object/enum-to-const-object.js';
import { extract } from './refactors/extract/extract.js';
import { extractClass } from './refactors/extract-class/extract-class.js';
import { extractInterface } from './refactors/extract-interface/extract-interface.js';
import { extractSuperclass } from './refactors/extract-superclass/extract-superclass.js';
import { extractType } from './refactors/extract-type/extract-type.js';
import { inlineField } from './refactors/inline-field/inline-field.js';
import { inlineFunction } from './refactors/inline-function/inline-function.js';
import { inlineTypeAlias } from './refactors/inline-type-alias/inline-type-alias.js';
import { inlineParameter } from './refactors/inline-parameter/inline-parameter.js';
import { inlineVariable } from './refactors/inline-variable/inline-variable.js';
import { introduceParameter } from './refactors/introduce-parameter/introduce-parameter.js';
import { invertBoolean } from './refactors/invert-boolean/invert-boolean.js';
import { makeReadonly } from './refactors/make-readonly/make-readonly.js';
import { moduleForm } from './refactors/module-form/module-form.js';
import { moveFile } from './refactors/move-file/move-file.js';
import { memberForm } from './refactors/member-form/member-form.js';
import { moveInstanceMethod } from './refactors/move-instance-method/move-instance-method.js';
import { moveMember } from './refactors/move-member/move-member.js';
import { moveSymbol } from './refactors/move-symbol/move-symbol.js';
import { rename } from './refactors/rename/rename.js';
import { safeDelete } from './refactors/safe-delete/safe-delete.js';
import { typeLoopholes } from './types/loopholes/loopholes.js';
import { pullMembersUp } from './refactors/pull-members-up/pull-members-up.js';
import { pushMembersDown } from './refactors/push-members-down/push-members-down.js';
import { staticForm } from './refactors/static-form/static-form.js';
import { widenType } from './refactors/widen-type/widen-type.js';

/**
 * Every shipped TypeScript tool, registered in the alphabetical order
 * the CLI and MCP listings display (the registry sorts regardless).
 */
export function createTsRegistry(): ToolRegistry {
  const registry = new ToolRegistry();
  registry.register(floatingPromises);
  registry.register(llmTells);
  registry.register(longComments);
  registry.register(staleRefs);
  registry.register(dupeFunctions);
  registry.register(importCycles);
  registry.register(deadExports);
  registry.register(changeSignature);
  registry.register(constructorToFactory);
  registry.register(enumToConstObject);
  registry.register(extract);
  registry.register(extractClass);
  registry.register(extractInterface);
  registry.register(extractSuperclass);
  registry.register(extractType);
  registry.register(inlineField);
  registry.register(inlineFunction);
  registry.register(inlineTypeAlias);
  registry.register(inlineParameter);
  registry.register(inlineVariable);
  registry.register(introduceParameter);
  registry.register(invertBoolean);
  registry.register(makeReadonly);
  registry.register(moduleForm);
  registry.register(moveFile);
  registry.register(memberForm);
  registry.register(moveInstanceMethod);
  registry.register(moveMember);
  registry.register(moveSymbol);
  registry.register(rename);
  registry.register(safeDelete);
  registry.register(typeLoopholes);
  registry.register(pullMembersUp);
  registry.register(pushMembersDown);
  registry.register(staticForm);
  registry.register(widenType);
  return registry;
}
